### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Baa14453** [troycurtisjr/gr-pager#7]
Hi,
Thanks for keeping this updated
I'm having trouble importing the library and it's shared libraries.

Initially I got the error:
```python
>>> import pager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pager'
```
I noticed it installed into `/usr/local/lib/python3/dist-packages/pager` but that wasn't on my sys.path, other packages installed instead into `/usr/local/lib/python3.8/dist-packages/`. I resolved this by linking `/usr/local/lib/python3.8/dist-packages/pager` to `/usr/local/lib/python3/dist-packages/pager` (`sudo ln -s /usr/local/lib/python3/dist-packages/pager /usr/local/lib/python3.8/dist-packages/pager`), this made the 'no module' error go away but I then got a new import error for the shared library:

```python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pager
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pager/__init__.py", line 33, in <module>
    from .pager_swig import *
  File "/usr/local/lib/python3.8/dist-packages/pager/pager_swig.py", line 13, in <module>
    from . import _pager_swig
ImportError: libgnuradio-pager.so.1.0.0git: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pager/__init__.py", line 37, in <module>
    from .pager_swig import *
  File "/usr/local/lib/python3.8/dist-packages/pager/pager_swig.py", line 13, in <module>
    from . import _pager_swig
ImportError: libgnuradio-pager.so.1.0.0git: cannot open shared object file: No such file or directory
>>> exit()
```

Running `sudo ldconfig` [then fixed this issue.](https://askubuntu.com/questions/350068/where-does-ubuntu-look-for-shared-libraries). I don't know if this requires updating for new package locations of Python in Ubuntu but it might help someone else.

**Comment by troycurtisjr** [comment]
Could you give some more details about your environment? Distribution and version as well as how you installed gnu radio (from source or from a package, of a package, from where).

It definitively seems surprising because I thought it would use the common files in gnu radio base distro in order to determine those paths.

**Comment by Baa14453** [comment]
I'm running `Ubuntu 20.04.3 LTS`. Installed the `gnuradio` package from default Apt repository.
I just tried to compile gr-osmosdr and got the same result. I don't know why `/usr/local/lib/python3/dist-packages/` isn't in my Python path, not sure if it's been officially moved to `/usr/local/lib/python3.8/dist-packages/` or if it's something else I've done.

**Comment by troycurtisjr** [comment]
Since this sounds more like a gnuradio installation issue and not something specific to gr-pager, I'm going to close this out.
